# Generated by Django 5.0.3 on 2025-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='description',
            field=models.TextField(default='No description for this group.', max_length=255),
        ),
    ]
